[package]
name = "tron"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
serde_json = "1"
base64 = "0.22"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
